package vista;

import controlador.ControladorServicio;
import controlador.ControladorUsuario;
import java.util.ArrayList;
import java.util.Calendar;
import modelo.Servicio;
import modelo.Usuario;
import modelo.Zona;
import modelo.ZonaDAO;
import utilerias.Conversion;
import utilerias.Mensaje;

/**
 *
 * @author Alejandro
 */
public class IRegistrarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form IRegistrarUsuario
     */
    private final int anio;
    private final int mes;
    public IRegistrarUsuario() {
        initComponents();
        Calendar c = Calendar.getInstance();
        anio = c.get(Calendar.YEAR);
        mes = c.get(Calendar.MONTH);
        for(int i = 0; i < jcbAnio.getItemCount(); i++){
            if(jcbAnio.getItemAt(i) == anio)
                jcbAnio.setSelectedIndex(i);
        }
        jcMes.setSelectedIndex(mes);
    }
    
    private void limpiar(){
        this.jtNDI.setText("");
        this.jtNombre.setText("");
        this.jtApellidos.setText("");
        this.jtTelefono.setText("");
        this.jtCalle.setText("");
        this.jtNumero.setText("");
        this.jtNodeMedidor.setText("");
        this.jtaNotas.setText("");
    }
    
    private void mostrarUsuario(Usuario us){
        this.jtNDI.setText(""+us.getNdi());
        this.jtNombre.setText(us.getNombre());
        this.jtApellidos.setText(us.getApellidos());
        this.jtTelefono.setText(us.getTelefono());             
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgConMedidor = new javax.swing.ButtonGroup();
        jpContenedor = new javax.swing.JPanel();
        jbGuardar = new javax.swing.JButton();
        jpContenedorUsuario = new javax.swing.JPanel();
        jtTelefono = new componente.DTexto();
        jlTelefono = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jtApellidos = new componente.DTexto();
        jtNombre = new componente.DTexto();
        jlNombre = new javax.swing.JLabel();
        jtNDI = new componente.NumeroEntero();
        jlNDI = new javax.swing.JLabel();
        jlEstado1 = new javax.swing.JLabel();
        jcMes = new javax.swing.JComboBox<>();
        jcbAnio = new javax.swing.JComboBox<>();
        jpContenedorServicio = new javax.swing.JPanel();
        jlCalle = new javax.swing.JLabel();
        jtCalle = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jlCuentaMedidor = new javax.swing.JLabel();
        jrbSI = new javax.swing.JRadioButton();
        jrbNO = new javax.swing.JRadioButton();
        jlNodeMedidor = new javax.swing.JLabel();
        jtNodeMedidor = new componente.DTexto();
        jlZona = new javax.swing.JLabel();
        jcbZona = new javax.swing.JComboBox<>();
        jlEstado = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jlNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaNotas = new javax.swing.JTextArea();
        jbCancelar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();

        this.jbgConMedidor.add(this.jrbNO);
        this.jbgConMedidor.add(this.jrbSI);

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jpContenedorUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedorUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Usuario")));

        jtTelefono.setRango(new char[] {'0'});

        jlTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTelefono.setText("Telefono:");

        jlApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlApellido.setText("Apellidos:");

        jtApellidos.setRango(new char[] {'A', ' '});
        jtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtApellidosFocusLost(evt);
            }
        });

        jtNombre.setRango(new char[] {'A', ' '});
        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombreFocusLost(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombre.setText("Nombre(s):");

        jtNDI.setText("");
        jtNDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNDIActionPerformed(evt);
            }
        });

        jlNDI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNDI.setText("NDI:");

        jlEstado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEstado1.setText("Fecha de Registro:");

        jcMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        for(int i = 2016; i <= 2030; i++){
            jcbAnio.addItem(i);
        }

        javax.swing.GroupLayout jpContenedorUsuarioLayout = new javax.swing.GroupLayout(jpContenedorUsuario);
        jpContenedorUsuario.setLayout(jpContenedorUsuarioLayout);
        jpContenedorUsuarioLayout.setHorizontalGroup(
            jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorUsuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTelefono)
                    .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpContenedorUsuarioLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jlApellido))
                        .addComponent(jlNombre))
                    .addComponent(jlNDI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtNDI, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlEstado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpContenedorUsuarioLayout.setVerticalGroup(
            jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEstado1)
                    .addComponent(jcbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNDI)
                    .addComponent(jtNDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpContenedorServicio.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedorServicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Servicio"));

        jlCalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlCalle.setText("Calle:");

        jtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCalleFocusLost(evt);
            }
        });

        jlNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNumero.setText("Número:");

        jtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumeroFocusLost(evt);
            }
        });

        jlCuentaMedidor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlCuentaMedidor.setText("¿Cuenta con medidor?");

        jrbSI.setBackground(new java.awt.Color(255, 255, 255));
        jrbSI.setText("SI");
        jrbSI.setSelected(true);
        jrbSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSIActionPerformed(evt);
            }
        });

        jrbNO.setBackground(new java.awt.Color(255, 255, 255));
        jrbNO.setText("NO");
        jrbNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNOActionPerformed(evt);
            }
        });

        jlNodeMedidor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNodeMedidor.setText("No. de Medidor:");

        jtNodeMedidor.setRango(new char[] {'0'});

        jlZona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlZona.setText("Zona:");

        ArrayList<Zona> alZonas = ZonaDAO.todasLasZonas();
        for(Zona z: alZonas)
        jcbZona.addItem(z);

        jlEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEstado.setText("Estado:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "CANCELADO" }));

        jlNotas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNotas.setText("Notas:");

        jtaNotas.setColumns(20);
        jtaNotas.setRows(5);
        jtaNotas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtaNotasFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jtaNotas);

        javax.swing.GroupLayout jpContenedorServicioLayout = new javax.swing.GroupLayout(jpContenedorServicio);
        jpContenedorServicio.setLayout(jpContenedorServicioLayout);
        jpContenedorServicioLayout.setHorizontalGroup(
            jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlZona)
                    .addComponent(jlNodeMedidor)
                    .addComponent(jlCalle)
                    .addComponent(jlNumero)
                    .addComponent(jlNotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jtNodeMedidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpContenedorServicioLayout.createSequentialGroup()
                        .addComponent(jcbZona, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpContenedorServicioLayout.createSequentialGroup()
                        .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpContenedorServicioLayout.createSequentialGroup()
                                .addComponent(jtNumero)
                                .addGap(18, 18, 18)
                                .addComponent(jlCuentaMedidor)
                                .addGap(18, 18, 18)
                                .addComponent(jrbSI)
                                .addGap(18, 18, 18)
                                .addComponent(jrbNO)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpContenedorServicioLayout.setVerticalGroup(
            jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlEstado)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlZona)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumero)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCuentaMedidor)
                    .addComponent(jrbSI)
                    .addComponent(jrbNO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNodeMedidor)
                    .addComponent(jtNodeMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedorServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNotas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedorUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpContenedorServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGuardar)
                .addContainerGap())
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addComponent(jpContenedorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContenedorServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbCancelar)
                    .addComponent(jbLimpiar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSIActionPerformed
        this.jtNodeMedidor.setText("");
        this.jtNodeMedidor.setEditable(true);
    }//GEN-LAST:event_jrbSIActionPerformed

    private void jtNDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNDIActionPerformed
       Usuario usuario= ControladorUsuario.validarConsultaUsuarioConNDI(
               Conversion.deStringAint(this.jtNDI.getText()));
       if(usuario != null){
           mostrarUsuario(usuario);
       }       
    }//GEN-LAST:event_jtNDIActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNdi(Conversion.deStringAint(this.jtNDI.getText()));
        usuario.setNombre(this.jtNombre.getText());
        usuario.setApellidos(this.jtApellidos.getText());
        usuario.setTelefono(this.jtTelefono.getText());
        
        Zona z = (Zona) this.jcbZona.getSelectedItem();
        Servicio serv = new Servicio();
        serv.setNdi_usuario(usuario.getNdi());
        serv.setCodigo_zona(z.getCodigo());
        serv.setEstado((String)this.jcbEstado.getSelectedItem());
        if(this.jrbSI.isSelected()){
            serv.setNo_medidor(Conversion.deStringAint(this.jtNodeMedidor.getText()));
            serv.setUsaMedidor("SI");
        }else{
            serv.setNo_medidor(0);
            serv.setUsaMedidor("NO");
        }
        serv.setCalle(this.jtCalle.getText());
        serv.setNumero_calle(this.jtNumero.getText());
        serv.setMes(this.jcMes.getSelectedIndex() + 1);
        serv.setAnio((int)this.jcbAnio.getSelectedItem());
        serv.setNotas(this.jtaNotas.getText());        
        boolean usuarioregistrado = ControladorUsuario.validarRegistroUsuario(usuario);
        boolean servicioregistrado = ControladorServicio.validarRegistroServicio(serv);
        
        if(usuarioregistrado && servicioregistrado){
            Mensaje.deInformacion("Cuenta registrada");
            IRegistrosUsuarios.actualizaTabla();
            limpiar();
            dispose();
        }        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jrbNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNOActionPerformed
        this.jtNodeMedidor.setText("NO APLICA");
        this.jtNodeMedidor.setEditable(false);
    }//GEN-LAST:event_jrbNOActionPerformed

    private void jtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusLost
        if(!this.jtNombre.getText().trim().isEmpty()){
            this.jtNombre.setText(jtNombre.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtNombreFocusLost

    private void jtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtApellidosFocusLost
        if(!this.jtApellidos.getText().trim().isEmpty()){
            this.jtApellidos.setText(jtApellidos.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtApellidosFocusLost

    private void jtCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCalleFocusLost
        if(!this.jtCalle.getText().trim().isEmpty()){
            this.jtCalle.setText(jtCalle.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtCalleFocusLost

    private void jtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroFocusLost
        if(!this.jtNumero.getText().trim().isEmpty()){
            this.jtNumero.setText(jtNumero.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtNumeroFocusLost

    private void jtaNotasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaNotasFocusLost
        if(!this.jtaNotas.getText().trim().isEmpty()){
            this.jtaNotas.setText(jtaNotas.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtaNotasFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.ButtonGroup jbgConMedidor;
    private javax.swing.JComboBox<String> jcMes;
    private javax.swing.JComboBox<Integer> jcbAnio;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<Zona> jcbZona;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCalle;
    private javax.swing.JLabel jlCuentaMedidor;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlEstado1;
    private javax.swing.JLabel jlNDI;
    private javax.swing.JLabel jlNodeMedidor;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNotas;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlZona;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpContenedorServicio;
    private javax.swing.JPanel jpContenedorUsuario;
    private javax.swing.JRadioButton jrbNO;
    private javax.swing.JRadioButton jrbSI;
    private componente.DTexto jtApellidos;
    private javax.swing.JTextField jtCalle;
    private componente.NumeroEntero jtNDI;
    private componente.DTexto jtNodeMedidor;
    private componente.DTexto jtNombre;
    private javax.swing.JTextField jtNumero;
    private componente.DTexto jtTelefono;
    private javax.swing.JTextArea jtaNotas;
    // End of variables declaration//GEN-END:variables
}
