package vista;

import controlador.AdminIFrame;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import modelo.Zona;
import modelo.ZonaDAO;
import modelo.ModelViewRecibo;
import modelo.ViewRecibo;
import modelo.ViewReciboDao;
/**
 *
 * @author Alejandro
 */
public class IRegistrosRecibos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IRegistroClientes
     */
    private JDesktopPane dp;
    public static ModelViewRecibo mdlRecibos;
    private static int mes;
    private static int anio;
    private int selectIndex;
    public static IRegistrarPago vtnRPago = null;
    
    public IRegistrosRecibos(JDesktopPane mainApp) {
        initComponents();
        dp = mainApp;
        //mes = this.jcMes.getSelectedIndex() + 1;
        //anio = (int) this.jcbAnio.getSelectedItem();      
        mdlRecibos = new ModelViewRecibo(ViewReciboDao.todosLosRecibos());
        jTablaRecibos.setModel(mdlRecibos);
        selectIndex = jTablaRecibos.getSelectedRow();
    }  
    
    public static final void actualizaTabla(){
        mdlRecibos = new ModelViewRecibo(mes, anio);
        jTablaRecibos.setModel(mdlRecibos);
    }
    
    public static final void actualizaTabla(ModelViewRecibo mvr){
        mdlRecibos = mvr;
        jTablaRecibos.setModel(mdlRecibos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbZonas = new javax.swing.JComboBox<>();
        jtNombre = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaRecibos = new javax.swing.JTable();
        jtfDireccion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbActualizar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtTotal = new componente.DTexto();
        jtDeuda = new componente.DTexto();
        jlDeuda = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbAnio = new javax.swing.JComboBox<>();
        jcMes = new javax.swing.JComboBox<>();
        jlMes = new javax.swing.JLabel();
        jlAnio = new javax.swing.JLabel();

        setClosable(true);
        setForeground(java.awt.Color.darkGray);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Usuarios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Zona t = new Zona(0, "TODAS");
        this.jcbZonas.addItem(t);
        ArrayList<Zona> alZonas= ZonaDAO.todasLasZonas();
        for(Zona z : alZonas)
        this.jcbZonas.addItem(z);

        jtNombre.setText("NOMBRE(S)");
        jtNombre.setToolTipText("NOMBRE(S)");
        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombreFocusLost(evt);
            }
        });

        jtfApellidos.setText("APELLIDOS");
        jtfApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfApellidosFocusLost(evt);
            }
        });

        jbBuscar.setText("BUSCAR");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jTablaRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablaRecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaRecibosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaRecibos);

        jtfDireccion.setText("DIRECCION");
        jtfDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDireccionFocusLost(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTA DE RECIBOS");

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        btnCobrar.setText("COBRAR");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCobrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalir)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalir)
                            .addComponent(btnCobrar)
                            .addComponent(jbActualizar))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setText("ZONA");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADEUDO", "PAGADO" }));

        jLabel3.setText("ESTADO");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jtTotal.setEditable(false);
        jtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtDeuda.setEditable(false);
        jtDeuda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jlDeuda.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlDeuda.setText("DEUDA:");
        jlDeuda.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("TOTAL:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDeuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDeuda)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        for(int i = 2016; i <= 2030; i++){
            jcbAnio.addItem(i);
        }

        jcMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        jlMes.setText("MES");

        jlAnio.setText("AÑO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMes, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlAnio)
                    .addComponent(jlMes))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jcbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusGained
        if(jtNombre.getText().equals("NOMBRE(S)")){
            jtNombre.setText("");
        }
    }//GEN-LAST:event_jtNombreFocusGained

    private void jtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusLost
        if(!this.jtNombre.getText().trim().isEmpty()){
            this.jtNombre.setText(jtNombre.getText().toUpperCase());
        }else{
            this.jtNombre.setText("NOMBRE(S)");
        }
    }//GEN-LAST:event_jtNombreFocusLost

    private void jtfApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidosFocusGained
        if(jtfApellidos.getText().equals("APELLIDOS")){
            this.jtfApellidos.setText("");
        }
    }//GEN-LAST:event_jtfApellidosFocusGained

    private void jtfApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidosFocusLost
        if(!this.jtfApellidos.getText().trim().isEmpty()){
            this.jtfApellidos.setText(jtfApellidos.getText().toUpperCase());
        }else{
            this.jtfApellidos.setText("APELLIDOS");
        }
    }//GEN-LAST:event_jtfApellidosFocusLost

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        ViewRecibo vr = new ViewRecibo();
        Zona z = (Zona) this.jcbZonas.getSelectedItem();
        
        vr.setAnio((int)this.jcbAnio.getSelectedItem());
        vr.setMes(this.jcMes.getSelectedIndex() + 1);        
        vr.setNombre(this.jtNombre.getText());
        vr.setApellidos(this.jtfApellidos.getText());
        vr.setCalle(this.jtfDireccion.getText());
        vr.setZona(z.getNombre());        
        vr.setEstado((String)this.jcbEstado.getSelectedItem());
        if(vr.getNombre().equals("NOMBRE(S)")){
            vr.setNombre("");
        }
        if(vr.getApellidos().equals("APELLIDOS")){
            vr.setApellidos("");
        }
        if(vr.getCalle().equals("DIRECCION")){
            vr.setCalle("");
        }
        if(z.getCodigo() == 0){
            vr.setZona("");
        }
        mdlRecibos = new ModelViewRecibo(ViewReciboDao.recibosComo(vr));
        jTablaRecibos.setModel(mdlRecibos);                     
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtfDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDireccionFocusGained
        if(jtfDireccion.getText().equals("DIRECCION")){
            jtfDireccion.setText("");
        }
    }//GEN-LAST:event_jtfDireccionFocusGained

    private void jtfDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDireccionFocusLost
        if(!this.jtfDireccion.getText().trim().isEmpty()){
            this.jtfDireccion.setText(jtfDireccion.getText().toUpperCase());
        }else{
            this.jtfDireccion.setText("DIRECCION");
        }
    }//GEN-LAST:event_jtfDireccionFocusLost

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        mdlRecibos = new ModelViewRecibo(ViewReciboDao.todosLosRecibos());
        jTablaRecibos.setModel(mdlRecibos);
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jTablaRecibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaRecibosMouseClicked
        ViewRecibo vr;
        ArrayList<ViewRecibo> listaRecibos; 
        selectIndex = jTablaRecibos.getSelectedRow();
        
        if(selectIndex != -1){
            vr = mdlRecibos.getViewRecibo(selectIndex);
            listaRecibos = ViewReciboDao.recibosdelServicio(vr.getId_servicio());
            jtDeuda.setText(""+vr.getMontoDouble());
            double monto = 0.0;
            for(ViewRecibo v: listaRecibos){
                if(v.getEstado().equals("ADEUDO"))
                    monto += v.getMontoDouble();
            }
            jtTotal.setText(""+monto);
        }
        /*
        if(selectIndex != -1){
            vr = mdlRecibos.getViewRecibo(selectIndex);
            listaRecibos = ReciboDAO.recibosSMDelUsuario(vr.getId_servicio(), false);               
            double monto = 0.0;
            for(int i = 0; i < listaRecibos.size(); i++){
                if(vr.getId_servicio() == listaRecibos.get(i).getId_servicio())
                    this.jtDeuda.setText(""+listaRecibos.get(i).getMontoDouble());
                monto += listaRecibos.get(i).getMontoDouble();
            }        
            this.jtTotal.setText(""+monto);
        }
        */
        //System.out.println(""+monto);        
    }//GEN-LAST:event_jTablaRecibosMouseClicked

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        int index = jTablaRecibos.getSelectedRow();
        ModelViewRecibo mvRecibos =  (ModelViewRecibo) jTablaRecibos.getModel(); 
        if(index != -1){
            ViewRecibo vr = mvRecibos.getViewRecibo(index);            
            if(vtnRPago== null){
                vtnRPago = new IRegistrarPago(vr); 
            }
            AdminIFrame.mostrarVentanaFactura(dp, vtnRPago);  
        }
        
    }//GEN-LAST:event_btnCobrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTablaRecibos;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcMes;
    private javax.swing.JComboBox<Integer> jcbAnio;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<Zona> jcbZonas;
    private javax.swing.JLabel jlAnio;
    private javax.swing.JLabel jlDeuda;
    private javax.swing.JLabel jlMes;
    private componente.DTexto jtDeuda;
    private javax.swing.JTextField jtNombre;
    private componente.DTexto jtTotal;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfDireccion;
    // End of variables declaration//GEN-END:variables
}
